# Generated by Django 2.0 on 2018-10-22 23:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sinopse', models.TextField(help_text='Escreva um                                         pequeno sumário sobre o filme.', max_length=1000)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('diretor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.Diretor')),
            ],
        ),
        migrations.CreateModel(
            name='FilmeInstancia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para um filme no estoque', primary_key=True, serialize=False)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Manutenção'), ('e', 'Emprestado'), ('d', 'Disponível'), ('r', 'Reservado')], default='m', help_text='Status do Filme', max_length=1)),
                ('filme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.Filme')),
            ],
            options={
                'ordering': ['data_devolucao'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Escreva um gênero                                         de um filme (i.e Ação)', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.ManyToManyField(help_text='Escolha um gênero                                         para esse filme.', to='catalogo.Genero'),
        ),
    ]
