# Generated by Django 2.1.2 on 2018-11-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmeinstancia',
            name='alugado_number',
            field=models.IntegerField(default=0),
        ),
    ]
